name: "build"
on: [push, pull_request]
env:
  TRIVY_VERSION: 0.38.1
  BATS_LIB_PATH: '/usr/lib/'

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: test message
        run: echo "hi, this is from a forked repo"

      - name: test message
        run: ls -lah
